language: ruby

rvm:
  # - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1
  - ruby-head
  - rbx-2
  - jruby-19mode
  - jruby-head

os:
  - linux
  - osx

branches:
  only:
    - master

gemfile:
  - Gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
